# Generated by Django 6.0.2 on 2026-02-13 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#667eea', help_text='Cor hex para gráficos', max_length=7)),
                ('icon', models.CharField(default='📁', help_text='Emoji/ícone', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-year', '-month', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Palavra-chave (case-insensitive)', max_length=100)),
                ('priority', models.IntegerField(default=0, help_text='Maior prioridade = processado primeiro')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='invoices.category')),
            ],
            options={
                'ordering': ['-priority', 'keyword'],
                'unique_together': {('keyword', 'category')},
            },
        ),
    ]
