# Generated by Django 6.0.2 on 2026-02-13 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_category_alter_invoice_options_invoice_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_predicted',
            field=models.BooleanField(default=False, help_text='Transação gerada automaticamente como previsão de parcelas futuras'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='invoices.invoice'),
        ),
    ]
