# Generated by Django 5.0.1 on 2026-03-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='recurring_group_id',
            field=models.CharField(blank=True, help_text='Agrupa entradas recorrentes para exclusão em lote', max_length=50, null=True),
        ),
    ]
