# Generated by Django 5.0.1 on 2026-03-09 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_income_recurring_group_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('expense', 'Despesa (Fatura)'), ('income', 'Receita (Entrada)')], default='expense', help_text='Define se é categoria de fatura ou de entrada', max_length=10),
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(blank=True, help_text='Categoria inferida automaticamente', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name', 'type')},
        ),
    ]
