# Generated by Django 5.0.1 on 2026-03-13 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_category_unique_together_category_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PixBoleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('category', models.CharField(blank=True, help_text='Categoria inferida automaticamente', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_boletos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pix/Boleto',
                'verbose_name_plural': 'Pix e Boletos',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
