# Generated by Django 5.0.1 on 2026-03-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_pixboleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixboleto',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pixboleto',
            name='recurring_group_id',
            field=models.CharField(blank=True, help_text='Agrupa saídas recorrentes para exclusão em lote', max_length=50, null=True),
        ),
    ]
